# -*- mode: ruby -*-
# vi: set ft=ruby :

# Define global variables
OS_BOX = "hashicorp/bionic64"

MASTER_NAME = "mashadS"

VAGRANT_PROVIDER = "virtualbox"

MASTER_IP		= "192.168.56.110"
MASTER_NETWORK	= "private_network"


CPU_VALUE     = 1
MEMORY_VALUE  = 1024

Vagrant.configure("2") do |config|
  # Selecting Virtual Machine Image
  config.vm.box = OS_BOX
  
  # Provision the K3s server
  config.vm.define MASTER_NAME do |server|
    # Set the Virtual machine Hostname
    server.vm.hostname = MASTER_NAME

    # Define network type, and inject the network IP address
		server.vm.network MASTER_NETWORK, ip: MASTER_IP

    # Forward http/80 port to our external machine
    server.vm.network :forwarded_port, guest: 80, host: 80

    # Configure Virtual Machine ressources
    server.vm.provider VAGRANT_PROVIDER do |vb|
      vb.cpus   = CPU_VALUE
      vb.name   = MASTER_NAME
      vb.memory = MEMORY_VALUE
    end

    # Installing K3s and required ressources
    server.vm.provision "shell",  path: "./scripts/setup-k3s.sh"

    # Deploying application and ingress
    server.vm.provision "shell",  path: "./scripts/deploy-app.sh"
  end
end
