# -*- mode: ruby -*-
# vi: set ft=ruby :

# Define global variables
OS_BOX = "bento/centos-7"
VAGRANT_PROVIDER = "virtualbox"
MEMORY_VALUE = 1024
CPU_VALUE = 1

Vagrant.configure("2") do |config|
  config.vm.box = OS_BOX

  # Provision the K3s server
  config.vm.define "mashadS" do |server|
    server.vm.hostname = "mashadS"
    server.vm.network "private_network", type: "dhcp"
    server.vm.network :forwarded_port, guest: 80, host: 80
    server.vm.provider VAGRANT_PROVIDER do |vb|
      vb.memory = MEMORY_VALUE
      vb.cpus = CPU_VALUE
    end
    server.vm.provision "shell", privileged: true, path: "./scripts/setup-k3s.sh"
  end
end
