# -*- mode: ruby -*-
# vi: set ft=ruby :

# Assign global variables
OS_BOX = "bento/centos-8"

VAGRANT_PROVIDER = "virtualbox"
NETWORK_TYPE = "private_network"

MEMORY_VALUE = 1024
CPU_VALUE = 1

SERVER_NAME = "mashadS"
SERVER_IP = "192.168.56.110"

AGENT_NAME = "mashadSW"
AGENT_IP = "192.168.56.111"



Vagrant.configure("2") do |config|
  config.vm.box = OS_BOX # Use the latest stable version of Ubuntu

  config.vm.provider VAGRANT_PROVIDER do |vb|
      vb.memory = MEMORY_VALUE  # 512 MB of RAM
      vb.cpus   = CPU_VALUE      # 1 CPU
      vb.name   = AGENT_NAME
    end
  # Define the specifications for controller machines
  
  config.vm.define SERVER_NAME do |controller|
    controller.vm.network NETWORK_TYPE, ip: SERVER_IP
    controller.vm.hostname = SERVER_NAME
    
    controller.vm.provision "shell", path: "./scripts/k3s_controller_install.sh"
  end
  
  # Define the specifications for agent machines
  
  config.vm.define AGENT_NAME do |agent|
    agent.vm.network NETWORK_TYPE, ip: AGENT_IP
    agent.vm.hostname = AGENT_NAME
    
    agent.vm.provision "shell", path: "./scripts/k3s_agent_install.sh"
  end
  
  
end
