# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Define the specifications for the machines
  config.vm.define "mashadS" do |server|
    server.vm.box = "centos/7"  # Use the latest stable version of Ubuntu
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 512  # 512 MB of RAM
      vb.cpus = 1      # 1 CPU
    end

    server.vm.hostname = "mashadS"
  end
end
