# -*- mode: ruby -*-
# vi: set ft=ruby :

# Assign global variables
OS_BOX = "bento/centos-7"
AGENT_NAME = 'gitlab'
VAGRANT_PROVIDER = "virtualbox"
NETWORK_TYPE = "private_network"

MEMORY_VALUE = 4024
CPU_VALUE = 4

AGENT_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = OS_BOX # Use the latest stable version of Ubuntu

  config.vm.provider VAGRANT_PROVIDER do |vb|
      vb.memory = MEMORY_VALUE  # 512 MB of RAM
      vb.cpus   = CPU_VALUE      # 1 CPU
  end
  
  # Define the specifications for agent machines
  config.vm.define AGENT_NAME do |gitlab|
    gitlab.vm.network "forwarded_port", guest: 8181, host: 8181, protocol: "tcp"
    gitlab.vm.network NETWORK_TYPE, ip: AGENT_IP
    gitlab.vm.hostname = AGENT_NAME
    gitlab.vm.provider VAGRANT_PROVIDER do |vb|
      vb.name = AGENT_NAME
    end
    # Deploying application and ingress
    gitlab.vm.provision "shell",  path: "./scripts/k3s_gitlab_agent.sh"
  end
  
end